# Generated by Django 5.2 on 2025-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('pages', models.IntegerField(null=True)),
                ('isbn', models.CharField(max_length=60)),
                ('short_description', models.TextField()),
                ('source', models.URLField(null=True)),
            ],
        ),
    ]
